name: CI · JSON Validate

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.webp'
      - '**/*.pdf'
      - '**/*.md'
      - 'private/infra/scripts/logs/**'
      - '**/legacy/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.webp'
      - '**/*.pdf'
      - '**/*.md'
      - 'private/infra/scripts/logs/**'
      - '**/legacy/**'
  workflow_dispatch: {}

permissions:
  contents: read

env:
  LOG_DIR: private/infra/scripts/logs
  SCHEMAS_DIR: private/quality/data-contracts
  NODE_VERSION: "20"

jobs:
  json_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure dirs
        run: mkdir -p "${LOG_DIR}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install AJV
        run: npm i -g ajv-cli ajv-formats

      - name: Validate JSON with AJV
        run: |
          set +e
          rc=0
          : > "$LOG_DIR/schemas_generic.txt"
          if [ -d "$SCHEMAS_DIR" ]; then
            for s in "$SCHEMAS_DIR"/*.schema.json; do
              [ -f "$s" ] || continue
              git ls-files | grep -Ei '\.json$' | grep -v '\.schema\.json' | while read -r d; do
                ajv -c ajv-formats -s "$s" -d "$d" --strict=false >> "$LOG_DIR/schemas_generic.txt" 2>&1 || rc=1
              done
            done
          fi
          echo "{\"ok\": $([ $rc -eq 0 ] && echo true || echo false) }" > "$LOG_DIR/json_validate_report.json"
          exit 0

      - name: Summary
        run: |
          echo "## JSON Validate" >> $GITHUB_STEP_SUMMARY
          echo "- LOG_DIR: \`${LOG_DIR}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Result:" >> $GITHUB_STEP_SUMMARY
          cat "${LOG_DIR}/json_validate_report.json" >> $GITHUB_STEP_SUMMARY || true

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: json-validate-${{ github.run_number }}
          path: |
            ${{ env.LOG_DIR }}/json_validate_report.json
            ${{ env.LOG_DIR }}/schemas_generic.txt
          if-no-files-found: warn
