name: CI · KPIs (generate + compose DevSecOps) with schema validation

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

permissions:
  contents: read

concurrency:
  group: ci-kpis-${{ github.ref }}
  cancel-in-progress: true

env:
  LOG_DIR: private/infra/scripts/logs
  SCHEMAS_DIR: private/quality/data-contracts
  PY_VERSION: '3.11'

jobs:
  kpis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare log dir
        run: mkdir -p "$LOG_DIR"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
          cache: 'pip'

      - name: Install CLI tools
        run: |
          pip install --upgrade jsonschema
          npm i -g ajv-cli ajv-formats

      - name: Generate KPIs
        run: |
          if [ -f "private/quality/pipelines/generate_kpis.py" ]; then
            python private/quality/pipelines/generate_kpis.py --out "$LOG_DIR/kpis_latest.json" || true
          else
            echo '{}' > "$LOG_DIR/kpis_latest.json"
          fi

      - name: Compose DevSecOps KPIs
        run: |
          if [ -f "private/quality/pipelines/build_devsecops_kpis.py" ]; then
            python private/quality/pipelines/build_devsecops_kpis.py \
              --in "$LOG_DIR/kpis_latest.json" --out "$LOG_DIR/devsecops_kpis.json" || true
          else
            cp "$LOG_DIR/kpis_latest.json" "$LOG_DIR/devsecops_kpis.json"
          fi

      - name: Validate KPIs schemas (AJV)
        run: |
          rc=0
          if [ -f "$SCHEMAS_DIR/kpis.schema.json" ] && [ -f "$LOG_DIR/kpis_latest.json" ]; then
            ajv -c ajv-formats -s "$SCHEMAS_DIR/kpis.schema.json" -d "$LOG_DIR/kpis_latest.json" --strict=false \
              > "$LOG_DIR/kpis_schema.txt" 2>&1 || rc=1
          fi
          if [ -f "$SCHEMAS_DIR/devsecops_kpis.schema.json" ] && [ -f "$LOG_DIR/devsecops_kpis.json" ]; then
            ajv -c ajv-formats -s "$SCHEMAS_DIR/devsecops_kpis.schema.json" -d "$LOG_DIR/devsecops_kpis.json" --strict=false \
              > "$LOG_DIR/devsecops_kpis_schema.txt" 2>&1 || rc=1
          fi
          echo "{\"ok\": $([ $rc -eq 0 ] && echo true || echo false) }" > "$LOG_DIR/kpis_schema_results.json"
          exit 0

      - name: Summary
        run: |
          echo "## KPIs" >> $GITHUB_STEP_SUMMARY
          echo "- Logs: \`$LOG_DIR\`" >> $GITHUB_STEP_SUMMARY
          ls -la "$LOG_DIR" >> $GITHUB_STEP_SUMMARY || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kpis-and-devsecops-${{ github.run_number }}
          path: ${{ env.LOG_DIR }}/**
          if-no-files-found: warn
