name: CI · DevSecOps KPIs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

env:
  LOG_DIR: private/infra/scripts/logs
  PY_VERSION: "3.11"

jobs:
  kpis:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
      - run: mkdir -p "${LOG_DIR}"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      - name: Build KPIs
        run: |
          python private/quality/pipelines/build_devsecops_kpis.py \
            --out "${LOG_DIR}/devsecops_kpis.json"
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devsecops-kpis
          path: ${{ env.LOG_DIR }}/devsecops_kpis.json
          if-no-files-found: warn
