name: CI · Security posture (scan + schema validation)

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

permissions:
  contents: read

concurrency:
  group: ci-security-posture-${{ github.ref }}
  cancel-in-progress: true

env:
  LOG_DIR: private/infra/scripts/logs
  SCHEMAS_DIR: private/quality/data-contracts
  PY_VERSION: '3.11'

jobs:
  security_posture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare log dir
        run: mkdir -p "$LOG_DIR"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
          cache: 'pip'

      - name: Install CLI tools
        run: |
          pip install --upgrade jsonschema
          npm i -g ajv-cli ajv-formats

      - name: Run security posture scan
        run: |
          if [ -f "private/quality/pipelines/sec_posture.py" ]; then
            python private/quality/pipelines/sec_posture.py --out "$LOG_DIR/security_posture.json" || true
          else
            echo '{}' > "$LOG_DIR/security_posture.json"
          fi

      - name: Validate schema (AJV)
        run: |
          rc=0
          if [ -f "$SCHEMAS_DIR/security_posture.schema.json" ] && [ -f "$LOG_DIR/security_posture.json" ]; then
            ajv -c ajv-formats -s "$SCHEMAS_DIR/security_posture.schema.json" \
                -d "$LOG_DIR/security_posture.json" --strict=false \
                > "$LOG_DIR/security_posture_schema.txt" 2>&1 || rc=1
          fi
          echo "{\"ok\": $([ $rc -eq 0 ] && echo true || echo false) }" > "$LOG_DIR/security_schema_results.json"
          exit 0

      - name: Summary
        run: |
          echo "## Security posture" >> $GITHUB_STEP_SUMMARY
          echo "- Logs: \`$LOG_DIR\`" >> $GITHUB_STEP_SUMMARY
          ls -la "$LOG_DIR" >> $GITHUB_STEP_SUMMARY || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-posture-${{ github.run_number }}
          path: ${{ env.LOG_DIR }}/**
          if-no-files-found: warn
