name: CI · Security Posture (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read

env:
  LOG_DIR: private/infra/scripts/logs
  PY_VERSION: "3.11"

jobs:
  sec_posture:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ env.PY_VERSION }} }
      - run: mkdir -p "${LOG_DIR}"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install trivy jsonschema
      - name: Generate security posture
        run: |
          python private/quality/pipelines/sec_posture.py \
            --out "${LOG_DIR}/security_posture.json"
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-posture
          path: ${{ env.LOG_DIR }}/security_posture.json
          if-no-files-found: warn
