# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Más GitHub Actions para Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - zdu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A1ABFFD958943DA8D4BC8287FC84693 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73422FB268614FA8A92B96095BF3B992 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2ACFE8D60E6C46BDA01C31573C799E7C }}

      - name: Upload file to Azure Blob
        run: |
          az storage blob upload \
            --account-name zdustorage \
            --container-name narrativas \
            --name index.html \
            --file narrativa/index.html \
            --auth-mode key \
            --account-key ${{ secrets.ZDU_STORAGE_KEY }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zdu'
          slot-name: 'Production'
          package: .
